'use strict';

const Order = require('../models/Order');
const ResellerProfile = require('../models/ResellerProfile');
const User = require('../models/User');
const LedgerEntry = require('../models/LedgerEntry');
const Source = require('../models/Source');

const ledger = require('./ledger');
const stock = require('./stock');
const pricing = require('./pricing');
const { getSettings } = require('./settings');
const { notify } = require('./notify');
const { withTransaction } = require('./tx');

const {
  ORDER_STATUS,
  ORDER_ORIGIN,
  PAYMENT_MODE,
  LEDGER_KIND,
  ROLES,
  EVENT_TYPE,
  KYC_STATUS,
} = require('../domain/constants');
const { assertCanTransition } = require('../domain/orderStateMachine');
const { generateOrderCode } = require('../utils/orderCode');
const { businessDate } = require('../utils/dhakaTime');
const { conflict, notFound, badRequest, forbidden } = require('../utils/errors');

/* ------------------------------------------------------------------ creation */

/**
 * A customer submission. Lands as pending and touches no money and no stock:
 * nothing is committed until the reseller confirms.
 *
 * The submissionId is generated by the browser when the form mounts. Disabling
 * the submit button is not a guard, because mobile Chrome on a flaky connection
 * retries the POST itself.
 */
async function createPendingOrder({ resellerProfile, paymentMode, customer, items, submissionId }) {
  if (resellerProfile.kycStatus !== KYC_STATUS.APPROVED || !resellerProfile.formActive) {
    throw forbidden('This shop is not accepting orders right now');
  }

  if (submissionId) {
    const existing = await Order.findOne({ reseller: resellerProfile._id, submissionId });
    if (existing) return { order: existing, duplicate: true };
  }

  const lines = await pricing.buildLines({ resellerId: resellerProfile._id, items });
  const { zone, chargePoisha } = await pricing.resolveDeliveryZone(customer.district);
  const totals = pricing.computeTotals(lines, chargePoisha);

  const order = await createWithUniqueCode({
    reseller: resellerProfile._id,
    origin: ORDER_ORIGIN.FORM,
    paymentMode,
    submissionId: submissionId || null,
    businessDate: businessDate(),
    customer,
    items: lines,
    deliveryZone: zone ? zone._id : null,
    deliveryZoneName: zone ? zone.name : null,
    deliveryChargePoisha: chargePoisha,
    totals,
    status: ORDER_STATUS.PENDING,
    statusHistory: [{ status: ORDER_STATUS.PENDING, at: new Date() }],
  });

  await notifyReseller(resellerProfile, EVENT_TYPE.ORDER_PENDING, {
    title: 'New order received',
    body: `${order.orderCode} from ${customer.name}`,
    data: { orderId: order._id, orderCode: order.orderCode },
  });

  return { order, duplicate: false };
}

/**
 * Order codes are random, so a collision is possible and cheap to retry.
 * A counter document would be a global hot spot conflicting with every
 * concurrent confirm, which is exactly what the money transaction cannot afford.
 */
async function createWithUniqueCode(doc, session, attempts = 5) {
  for (let i = 0; i < attempts; i += 1) {
    try {
      const payload = { ...doc, orderCode: generateOrderCode() };
      // eslint-disable-next-line no-await-in-loop
      const [created] = await Order.create([payload], session ? { session } : {});
      return created;
    } catch (err) {
      const isCodeCollision = err && err.code === 11000 && err.keyPattern && err.keyPattern.orderCode;
      if (!isCodeCollision || i === attempts - 1) throw err;
    }
  }
  throw conflict('ORDER_CODE', 'Could not allocate an order code, please retry');
}

/* ----------------------------------------------------------------- confirming */

/**
 * The critical path. One transaction, and nothing in it that is not required to
 * be atomic: claim the order, re-price against live catalog data, take stock,
 * move money. Notifications happen after commit, because the callback is retried.
 */
async function confirmOrder({ orderId, resellerProfile, actorUser, itemOverrides = [], paymentMode }) {
  const result = await withTransaction(async (session) => {
    // The status predicate is the lock. A second tab gets null and a clean 409.
    const claimed = await Order.findOneAndUpdate(
      { _id: orderId, reseller: resellerProfile._id, status: ORDER_STATUS.PENDING },
      { $set: { status: ORDER_STATUS.CONFIRMED } },
      { new: true, session }
    );

    if (!claimed) {
      const exists = await Order.findOne({ _id: orderId, reseller: resellerProfile._id }).session(session);
      if (!exists) throw notFound('Order not found');
      throw conflict('ALREADY_HANDLED', `This order is already ${exists.status}`);
    }

    assertCanTransition({ status: ORDER_STATUS.PENDING }, 'confirm', ROLES.RESELLER);

    // Re-price from live catalog data. The owner may have raised the cost price
    // since the customer submitted, and the floor must hold against today's cost.
    const overrideByProduct = new Map(itemOverrides.map((o) => [String(o.product), o]));
    const items = claimed.items.map((line) => {
      const override = overrideByProduct.get(String(line.product));
      return {
        product: line.product,
        qtyMilli: override && override.qtyMilli != null ? override.qtyMilli : line.qtyMilli,
        sellPricePoisha:
          override && override.sellPricePoisha != null
            ? override.sellPricePoisha
            : line.sellPricePoisha,
      };
    });

    const lines = await pricing.buildLines({ session, resellerId: resellerProfile._id, items });
    const totals = pricing.computeTotals(lines, claimed.deliveryChargePoisha);

    await stock.decrement(session, lines);

    const now = new Date();
    claimed.items = lines;
    claimed.totals = totals;
    claimed.confirmedAt = now;
    if (paymentMode) claimed.paymentMode = paymentMode;
    claimed.statusHistory.push({ status: ORDER_STATUS.CONFIRMED, at: now, by: actorUser._id });
    await claimed.save({ session });

    await postConfirmationEntries(session, claimed, actorUser);

    return claimed;
  });

  await notifyOwner(EVENT_TYPE.ORDER_CONFIRMED, {
    title: 'Order confirmed by reseller',
    body: `${result.orderCode} is ready to accept`,
    data: { orderId: result._id, orderCode: result.orderCode },
  });

  return result;
}

/**
 * Two entries, never one. A refused delivery reverses the goods while the courier
 * was still paid, which is a one-line reversal with two entries and a data
 * correction with one. See docs/adr/0003.
 */
async function postConfirmationEntries(session, order, actorUser) {
  await ledger.postEntry(session, {
    reseller: order.reseller,
    kind: LEDGER_KIND.ORDER_COST_DEBIT,
    amountPoisha: -order.totals.costSubtotalPoisha,
    idempotencyKey: ledger.keys.orderCost(order._id),
    refType: 'order',
    refId: order._id,
    note: `Goods for ${order.orderCode}`,
    createdBy: actorUser ? actorUser._id : null,
  });

  if (order.deliveryChargePoisha > 0) {
    await ledger.postEntry(session, {
      reseller: order.reseller,
      kind: LEDGER_KIND.DELIVERY_DEBIT,
      amountPoisha: -order.deliveryChargePoisha,
      idempotencyKey: ledger.keys.orderDelivery(order._id),
      refType: 'order',
      refId: order._id,
      note: `Delivery for ${order.orderCode}`,
      createdBy: actorUser ? actorUser._id : null,
    });
  }
}

/**
 * A reseller taking an order over the phone. Same order, same money, but it
 * skips pending because the reseller already has the customer on the line.
 */
async function createManualOrder({ resellerProfile, actorUser, paymentMode, customer, items }) {
  if (resellerProfile.kycStatus !== KYC_STATUS.APPROVED) {
    throw forbidden('Your KYC verification must be approved before you can take orders');
  }

  const order = await withTransaction(async (session) => {
    const lines = await pricing.buildLines({ session, resellerId: resellerProfile._id, items });
    const { zone, chargePoisha } = await pricing.resolveDeliveryZone(customer.district, session);
    const totals = pricing.computeTotals(lines, chargePoisha);

    await stock.decrement(session, lines);

    const now = new Date();
    const created = await createWithUniqueCode(
      {
        reseller: resellerProfile._id,
        origin: ORDER_ORIGIN.MANUAL,
        paymentMode,
        businessDate: businessDate(),
        customer,
        items: lines,
        deliveryZone: zone ? zone._id : null,
        deliveryZoneName: zone ? zone.name : null,
        deliveryChargePoisha: chargePoisha,
        totals,
        status: ORDER_STATUS.CONFIRMED,
        confirmedAt: now,
        statusHistory: [{ status: ORDER_STATUS.CONFIRMED, at: now, by: actorUser._id }],
      },
      session
    );

    await postConfirmationEntries(session, created, actorUser);
    return created;
  });

  await notifyOwner(EVENT_TYPE.ORDER_CONFIRMED, {
    title: 'Manual order created',
    body: `${order.orderCode} is ready to accept`,
    data: { orderId: order._id, orderCode: order.orderCode },
  });

  return order;
}

/* ---------------------------------------------------------------- transitions */

const EVENT_FOR_ACTION = {
  accept: EVENT_TYPE.ORDER_ACCEPTED,
  ship: EVENT_TYPE.ORDER_SHIPPED,
  deliver: EVENT_TYPE.ORDER_DELIVERED,
  cancel: EVENT_TYPE.ORDER_CANCELLED,
  return: EVENT_TYPE.ORDER_RETURNED,
};

/**
 * Every status change after confirm goes through here. The transition table
 * decides what is allowed, what the ledger posts and whether stock comes back.
 */
async function transitionOrder({ orderId, action, actorUser, role, resellerProfile, payload = {} }) {
  const settings = await getSettings();

  const order = await withTransaction(async (session) => {
    const scope = { _id: orderId };
    if (role === ROLES.RESELLER) scope.reseller = resellerProfile._id;

    const current = await Order.findOne(scope).session(session);
    if (!current) throw notFound('Order not found');

    const transition = assertCanTransition(current, action, role);

    if (transition.requiresCourier && !payload.courierName) {
      throw badRequest('COURIER_REQUIRED', 'Courier name is required to ship an order', {
        courierName: 'Required',
      });
    }

    /*
     * Resolved before the claim, so a bad source aborts without having moved the
     * order. It reads Source inside the transaction because an archive racing an
     * accept should be seen consistently with the write that follows it.
     */
    const sourceAssignments = transition.requiresSources
      ? await resolveSources(session, current, payload.sources)
      : null;

    // Claim with a status guard so two owners clicking at once cannot both win.
    const claimed = await Order.findOneAndUpdate(
      { ...scope, status: current.status },
      { $set: { status: transition.to } },
      { new: true, session }
    );
    if (!claimed) throw conflict('ALREADY_HANDLED', 'This order was just changed by someone else');

    await applyLedgerEffect(session, claimed, transition, actorUser, settings);

    if (transition.stock === 'restore' && claimed.confirmedAt) {
      await stock.restore(session, claimed.items);
    }

    /*
     * The name is copied onto the line, not just the id. From here on the order
     * renders its own history even if the source is renamed or archived, which
     * is the same promise the price snapshot already makes.
     */
    if (sourceAssignments) {
      claimed.items.forEach((item) => {
        const assigned = sourceAssignments.get(String(item._id));
        item.source = assigned._id;
        item.sourceNameBn = assigned.name;
      });
    }

    const now = new Date();
    if (transition.timestampField) claimed[transition.timestampField] = now;
    if (action === 'cancel') {
      claimed.cancelReason = payload.reason;
      claimed.cancelledBy = actorUser._id;
    }
    if (transition.requiresCourier) {
      claimed.courier = { name: payload.courierName, trackingNumber: payload.trackingNumber };
    }
    claimed.statusHistory.push({
      status: transition.to,
      at: now,
      by: actorUser._id,
      note: payload.reason || payload.note,
    });
    await claimed.save({ session });

    return claimed;
  });

  const eventType = EVENT_FOR_ACTION[action];
  if (eventType) {
    const profile = await ResellerProfile.findById(order.reseller);
    await notifyReseller(profile, eventType, {
      title: `Order ${order.orderCode} is ${order.status}`,
      body: payload.reason || undefined,
      data: { orderId: order._id, orderCode: order.orderCode, status: order.status },
    });
  }

  return order;
}

/**
 * Turns the owner's chosen sources into one source document per line.
 *
 * Every line needs one. A half-assigned order is worse than an unassigned one:
 * the packing list would look complete while quietly omitting where two of the
 * crates are meant to come from, and nothing downstream would notice.
 *
 * Archived sources are refused. Archiving is how the owner retires an orchard,
 * and a retired orchard is not somewhere today's order can be collected from,
 * even though every order that already names it keeps rendering perfectly.
 */
async function resolveSources(session, order, assignments) {
  const chosen = new Map(
    (assignments || []).map((entry) => [String(entry.itemId), String(entry.sourceId)])
  );

  const missing = order.items.filter((item) => !chosen.has(String(item._id)));
  if (missing.length > 0) {
    throw badRequest('SOURCE_REQUIRED', 'Choose a source for every item before accepting', {
      sources: `Missing for ${missing.length} item(s)`,
    });
  }

  const wanted = [...new Set(chosen.values())];
  const sources = await Source.find({ _id: { $in: wanted }, isArchived: false }).session(session);
  const byId = new Map(sources.map((source) => [String(source._id), source]));

  const unknown = wanted.filter((id) => !byId.has(id));
  if (unknown.length > 0) {
    throw badRequest('SOURCE_UNKNOWN', 'One of those sources no longer exists', {
      sources: 'Unknown or archived source',
    });
  }

  return new Map(
    order.items.map((item) => [String(item._id), byId.get(chosen.get(String(item._id)))])
  );
}

/** Applies whatever the transition table says this change does to the ledger. */
async function applyLedgerEffect(session, order, transition, actorUser, settings) {
  if (!transition.ledger) return;

  if (transition.ledger === 'codCollection') {
    // Prepaid orders post nothing on delivery: the reseller already has the money.
    if (order.paymentMode !== PAYMENT_MODE.COD) return;

    await ledger.postEntry(session, {
      reseller: order.reseller,
      kind: LEDGER_KIND.COD_COLLECTION_CREDIT,
      amountPoisha: order.totals.customerTotalPoisha,
      idempotencyKey: ledger.keys.codCollection(order._id),
      refType: 'order',
      refId: order._id,
      note: `Cash collected for ${order.orderCode}`,
      createdBy: actorUser._id,
      enforceCreditLimit: false,
    });
    return;
  }

  // An order that never reached confirmed has no entries to reverse.
  if (!order.confirmedAt) return;

  const open = await ledger.entriesFor('order', order._id, session);

  for (const entry of open) {
    // A returned parcel still cost a courier fee, so the delivery debit stands
    // unless the owner has chosen otherwise.
    const keepDeliveryCharge =
      transition.ledger === 'reverseOnReturn' &&
      entry.kind === LEDGER_KIND.DELIVERY_DEBIT &&
      !settings.reverseDeliveryChargeOnReturn;

    if (keepDeliveryCharge) continue;

    // eslint-disable-next-line no-await-in-loop
    await ledger.postReversal(session, entry, {
      reason: transition.to,
      note: `${order.orderCode} ${transition.to}`,
      createdBy: actorUser._id,
    });
  }
}

/* -------------------------------------------------------------- notifications */

async function notifyReseller(profile, eventType, message) {
  if (!profile) return;
  const user = await User.findById(profile.user);
  await notify({ user, eventType, ...message });
}

async function notifyOwner(eventType, message) {
  const owner = await User.findOne({ role: ROLES.OWNER });
  await notify({ user: owner, eventType, ...message });
}

/** Confirmed orders going stale while the fruit does not wait. */
async function agingOrders(hours) {
  const cutoff = new Date(Date.now() - hours * 60 * 60 * 1000);
  return Order.find({ status: ORDER_STATUS.CONFIRMED, confirmedAt: { $lt: cutoff } })
    .sort({ confirmedAt: 1 })
    .populate('reseller', 'shopName slug');
}

module.exports = {
  createPendingOrder,
  createManualOrder,
  confirmOrder,
  transitionOrder,
  agingOrders,
  postConfirmationEntries,
  LedgerEntry,
};
