'use strict';

const Order = require('../models/Order');
const ResellerProfile = require('../models/ResellerProfile');
const User = require('../models/User');
const LedgerEntry = require('../models/LedgerEntry');
const Source = require('../models/Source');

const ledger = require('./ledger');
const stock = require('./stock');
const pricing = require('./pricing');
const { getSettings } = require('./settings');
const { notify } = require('./notify');
const customers = require('./customers');
const { withTransaction } = require('./tx');
const customerSms = require('./customerSms');
const { enqueueCustomerSms } = require('./outbox');
const { ACTIONS: CUSTOMER_SMS_ACTIONS } = require('../domain/customerSms');

const {
  ORDER_STATUS,
  ORDER_ORIGIN,
  PAYMENT_MODE,
  LEDGER_KIND,
  ROLES,
  EVENT_TYPE,
  KYC_STATUS,
  SYSTEM_ACTOR,
  RESELLER_DEACTIVATED_REASON,
} = require('../domain/constants');
const {
  assertCanTransition,
  assertDeliveryChargeEditable,
  assertCustomerEditable,
  SYSTEM_CANCELLABLE,
  getTransition,
  wasCommitted,
} = require('../domain/orderStateMachine');
const { shopAvailability } = require('../domain/shop');
const { generateOrderCode } = require('../utils/orderCode');
const { businessDate } = require('../utils/dhakaTime');
const { toTaka } = require('../utils/money');
const { conflict, notFound, badRequest, forbidden } = require('../utils/errors');

/* ------------------------------------------------------------------ creation */

/**
 * A customer submission. Lands as pending and touches no money and no stock:
 * nothing is committed until the reseller confirms.
 *
 * The submissionId is generated by the browser when the form mounts. Disabling
 * the submit button is not a guard, because mobile Chrome on a flaky connection
 * retries the POST itself.
 */
async function createPendingOrder({ resellerProfile, paymentMode, customer, items, submissionId }) {
  // The same answer the shop page gives, so the page never invites an order this
  // refuses. A deactivated reseller's shop is closed whatever the profile says.
  const account = await User.findById(resellerProfile.user).select('isActive');
  const availability = shopAvailability(resellerProfile, account);
  if (!availability.acceptingOrders) {
    const err = conflict('SHOP_NOT_ACCEPTING', 'This shop is not accepting orders right now');
    err.fields = { reason: availability.reason };
    throw err;
  }

  if (submissionId) {
    const existing = await Order.findOne({ reseller: resellerProfile._id, submissionId });
    if (existing) return { order: existing, duplicate: true };
  }

  const lines = await pricing.buildLines({ resellerId: resellerProfile._id, items });
  const { zone, chargePoisha } = await pricing.resolveDeliveryZone(customer.district);
  const totals = pricing.computeTotals(lines, chargePoisha);

  let order;
  try {
    order = await createWithUniqueCode({
      reseller: resellerProfile._id,
      origin: ORDER_ORIGIN.FORM,
      paymentMode,
      submissionId: submissionId || null,
      businessDate: businessDate(),
      customer,
      items: lines,
      deliveryZone: zone ? zone._id : null,
      deliveryZoneName: zone ? zone.name : null,
      deliveryChargePoisha: chargePoisha,
      totals,
      status: ORDER_STATUS.PENDING,
      statusHistory: [{ status: ORDER_STATUS.PENDING, at: new Date() }],
    });
  } catch (err) {
    /*
     * Two identical submissions raced past the lookup above, and the unique
     * index let exactly one of them in. The loser is the same customer pressing
     * the same button, so it gets the winner's order, not an error.
     */
    const isSameSubmission =
      submissionId && err && err.code === 11000 && err.keyPattern && err.keyPattern.submissionId;
    if (!isSameSubmission) throw err;

    const existing = await Order.findOne({ reseller: resellerProfile._id, submissionId });
    if (!existing) throw err;
    return { order: existing, duplicate: true };
  }

  /*
   * Outside the transaction and never able to fail it. The customer record is a
   * projection of this collection, so a missed update is recomputed by
   * `customers.rebuild`, while a refused order is simply lost business.
   */
  await customers.recordOrder(order);

  await notifyReseller(resellerProfile, EVENT_TYPE.ORDER_PENDING, {
    data: { orderId: order._id, orderCode: order.orderCode, customerName: customer.name },
  });

  return { order, duplicate: false };
}

/**
 * Order codes are random, so a collision is possible and cheap to retry.
 * A counter document would be a global hot spot conflicting with every
 * concurrent confirm, which is exactly what the money transaction cannot afford.
 */
async function createWithUniqueCode(doc, session, attempts = 5) {
  for (let i = 0; i < attempts; i += 1) {
    try {
      const payload = { ...doc, orderCode: generateOrderCode() };
      // eslint-disable-next-line no-await-in-loop
      const [created] = await Order.create([payload], session ? { session } : {});
      return created;
    } catch (err) {
      const isCodeCollision = err && err.code === 11000 && err.keyPattern && err.keyPattern.orderCode;
      if (!isCodeCollision || i === attempts - 1) throw err;
    }
  }
  throw conflict('ORDER_CODE', 'Could not allocate an order code, please retry');
}

/* ----------------------------------------------------------------- confirming */

/**
 * The critical path. One transaction, and nothing in it that is not required to
 * be atomic: claim the order, re-price against live catalog data, take stock,
 * move money. Notifications happen after commit, because the callback is retried.
 */
async function confirmOrder({ orderId, resellerProfile, actorUser, itemOverrides = [], paymentMode }) {
  const result = await withTransaction(async (session) => {
    const scope = { _id: orderId, reseller: resellerProfile._id };

    // Validated before the claim, so an order in the wrong state gets the same
    // INVALID_TRANSITION answer every other lifecycle action gives.
    const current = await Order.findOne(scope).session(session);
    if (!current) throw notFound('Order not found');
    assertCanTransition(current, 'confirm', ROLES.RESELLER);

    // The status predicate is the lock. A second tab racing this one gets null
    // and a clean 409.
    const claimed = await Order.findOneAndUpdate(
      { ...scope, status: ORDER_STATUS.PENDING },
      { $set: { status: ORDER_STATUS.CONFIRMED } },
      { new: true, session }
    );
    if (!claimed) throw conflict('ALREADY_HANDLED', 'This order was just changed by someone else');

    // Re-price from live catalog data. The owner may have raised the cost price
    // since the customer submitted, and the floor must hold against today's cost.
    const overrideByProduct = new Map(itemOverrides.map((o) => [String(o.product), o]));
    const items = claimed.items.map((line) => {
      const override = overrideByProduct.get(String(line.product));
      return {
        product: line.product,
        qtyMilli: override && override.qtyMilli != null ? override.qtyMilli : line.qtyMilli,
        sellPricePoisha:
          override && override.sellPricePoisha != null
            ? override.sellPricePoisha
            : line.sellPricePoisha,
      };
    });

    const lines = await pricing.buildLines({ session, resellerId: resellerProfile._id, items });
    const totals = pricing.computeTotals(lines, claimed.deliveryChargePoisha);

    await stock.decrement(session, lines);

    const now = new Date();
    claimed.items = lines;
    claimed.totals = totals;
    claimed.confirmedAt = now;

    /*
     * The customer may have picked cash on delivery and then paid by bKash
     * before the reseller got to the order. The reseller may correct that here,
     * and only here: from confirm onwards the mode is fixed. See docs/adr/0007.
     */
    const historyEntry = { status: ORDER_STATUS.CONFIRMED, at: now, by: actorUser._id };
    if (paymentMode && paymentMode !== claimed.paymentMode) {
      historyEntry.paymentModeFrom = claimed.paymentMode;
      historyEntry.paymentModeTo = paymentMode;
      historyEntry.note = `Payment mode changed from ${claimed.paymentMode} to ${paymentMode}`;
      claimed.paymentMode = paymentMode;
    }
    claimed.statusHistory.push(historyEntry);
    await claimed.save({ session });

    await postConfirmationEntries(session, claimed, actorUser);

    return claimed;
  });

  /*
   * The owner's cue to act. A confirmed order is one the reseller has committed
   * to and the owner has not yet seen, so it names the shop it came from: the
   * owner's next question is always whose order it is.
   */
  await notifyOwner(EVENT_TYPE.ORDER_CONFIRMED, {
    data: {
      orderId: result._id,
      orderCode: result.orderCode,
      shopName: resellerProfile?.shopName,
    },
  });

  return result;
}

/**
 * Two entries, never one. A refused delivery reverses the goods while the courier
 * was still paid, which is a one-line reversal with two entries and a data
 * correction with one. See docs/adr/0003.
 */
async function postConfirmationEntries(session, order, actorUser) {
  await ledger.postEntry(session, {
    reseller: order.reseller,
    kind: LEDGER_KIND.ORDER_COST_DEBIT,
    amountPoisha: -order.totals.costSubtotalPoisha,
    idempotencyKey: ledger.keys.orderCost(order._id),
    refType: 'order',
    refId: order._id,
    note: `Goods for ${order.orderCode}`,
    createdBy: actorUser ? actorUser._id : null,
  });

  if (order.deliveryChargePoisha > 0) {
    await ledger.postEntry(session, {
      reseller: order.reseller,
      kind: LEDGER_KIND.DELIVERY_DEBIT,
      amountPoisha: -order.deliveryChargePoisha,
      idempotencyKey: ledger.keys.orderDelivery(order._id),
      refType: 'order',
      refId: order._id,
      note: `Delivery for ${order.orderCode}`,
      createdBy: actorUser ? actorUser._id : null,
    });
  }
}

/**
 * A reseller taking an order over the phone. Same order, same money, but it
 * skips pending because the reseller already has the customer on the line.
 */
async function createManualOrder({ resellerProfile, actorUser, paymentMode, customer, items }) {
  if (resellerProfile.kycStatus !== KYC_STATUS.APPROVED) {
    throw forbidden('Your KYC verification must be approved before you can take orders');
  }

  const order = await withTransaction(async (session) => {
    const lines = await pricing.buildLines({ session, resellerId: resellerProfile._id, items });
    const { zone, chargePoisha } = await pricing.resolveDeliveryZone(customer.district, session);
    const totals = pricing.computeTotals(lines, chargePoisha);

    await stock.decrement(session, lines);

    const now = new Date();
    const created = await createWithUniqueCode(
      {
        reseller: resellerProfile._id,
        origin: ORDER_ORIGIN.MANUAL,
        paymentMode,
        businessDate: businessDate(),
        customer,
        items: lines,
        deliveryZone: zone ? zone._id : null,
        deliveryZoneName: zone ? zone.name : null,
        deliveryChargePoisha: chargePoisha,
        totals,
        status: ORDER_STATUS.CONFIRMED,
        confirmedAt: now,
        statusHistory: [{ status: ORDER_STATUS.CONFIRMED, at: now, by: actorUser._id }],
      },
      session
    );

    await postConfirmationEntries(session, created, actorUser);
    return created;
  });

  await customers.recordOrder(order);

  // A manual order is confirmed the moment it is created, so the owner hears
  // about it the same way and through the same event as a form order.
  await notifyOwner(EVENT_TYPE.ORDER_CONFIRMED, {
    data: {
      orderId: order._id,
      orderCode: order.orderCode,
      shopName: resellerProfile?.shopName,
    },
  });

  return order;
}

/* ------------------------------------------------------------ delivery charge */

/**
 * The zone charge is a default, not a rule. The owner learns the real courier
 * cost at accept or ship, so it stays editable until the parcel has left.
 * See docs/adr/0010.
 *
 * Before confirm this only rewrites the order. After confirm the delivery debit
 * has already posted and is never edited, so the difference posts as its own
 * DELIVERY_ADJUSTMENT entry: negative for a raise, positive for a cut. The
 * guarded update and the entry are one transaction, so a confirm racing this
 * change sees either the old charge with no adjustment or the new charge with
 * one, never a mixture.
 *
 * An adjustment bypasses the credit limit. It is the owner recording what the
 * courier actually charged, not the reseller taking on a new commitment.
 *
 * @returns {Promise<{ order: object, beforePoisha: number, entry: object|null }>}
 */
async function changeDeliveryCharge({ orderId, deliveryChargePoisha, actorUser }) {
  return withTransaction(async (session) => {
    const current = await Order.findById(orderId).session(session);
    if (!current) throw notFound('Order not found');
    assertDeliveryChargeEditable(current);

    const beforePoisha = current.deliveryChargePoisha;
    const deltaPoisha = deliveryChargePoisha - beforePoisha;
    if (deltaPoisha === 0) return { order: current, beforePoisha, entry: null };

    const charged = wasCommitted(current.status);

    // Guarded on the status and the charge that were read, so a ship or a second
    // owner tab landing in between turns this into a clean 409 instead of an
    // adjustment computed against a stale charge.
    const update = {
      $set: {
        deliveryChargePoisha,
        'totals.walletDebitPoisha': current.totals.costSubtotalPoisha + deliveryChargePoisha,
        'totals.customerTotalPoisha': current.totals.sellSubtotalPoisha + deliveryChargePoisha,
      },
    };
    if (charged) update.$inc = { deliveryAdjustmentCount: 1 };

    const updated = await Order.findOneAndUpdate(
      { _id: current._id, status: current.status, deliveryChargePoisha: beforePoisha },
      update,
      { new: true, session }
    );
    if (!updated) throw conflict('ALREADY_HANDLED', 'This order was just changed by someone else');

    let entry = null;
    if (charged) {
      entry = await ledger.postEntry(session, {
        reseller: updated.reseller,
        kind: LEDGER_KIND.DELIVERY_ADJUSTMENT,
        amountPoisha: -deltaPoisha,
        idempotencyKey: ledger.keys.deliveryAdjustment(updated._id, updated.deliveryAdjustmentCount),
        refType: 'order',
        refId: updated._id,
        note: `Delivery for ${updated.orderCode} changed from ${toTaka(beforePoisha)} to ${toTaka(deliveryChargePoisha)} taka`,
        createdBy: actorUser ? actorUser._id : null,
        bypassCreditLimit: true,
      });
    }

    return { order: updated, beforePoisha, entry };
  });
}

/* ---------------------------------------------------------------- transitions */

const EVENT_FOR_ACTION = {
  accept: EVENT_TYPE.ORDER_ACCEPTED,
  ship: EVENT_TYPE.ORDER_SHIPPED,
  deliver: EVENT_TYPE.ORDER_DELIVERED,
  cancel: EVENT_TYPE.ORDER_CANCELLED,
  return: EVENT_TYPE.ORDER_RETURNED,
};

/**
 * Every status change after confirm goes through here. The transition table
 * decides what is allowed, what the ledger posts and whether stock comes back.
 */
async function transitionOrder({
  orderId,
  action,
  actorUser,
  role,
  resellerProfile,
  payload = {},
  /*
   * The owner's "send SMS to customer" box on accept, ship and cancel. Checked
   * before anything is claimed, so a missing gateway refuses the whole action
   * rather than moving the order and silently dropping the message.
   */
  sendCustomerSms = false,
}) {
  if (sendCustomerSms) {
    if (role !== ROLES.OWNER || !CUSTOMER_SMS_ACTIONS.includes(action)) {
      throw badRequest('INVALID_ACTION', 'Customer SMS is only sent on accept, ship or cancel');
    }
    customerSms.assertAvailable();
  }

  const settings = await getSettings();

  const order = await withTransaction(async (session) => {
    const scope = { _id: orderId };
    if (role === ROLES.RESELLER) scope.reseller = resellerProfile._id;

    const current = await Order.findOne(scope).session(session);
    if (!current) throw notFound('Order not found');

    const transition = assertCanTransition(current, action, role);

    if (transition.requiresCourier && !payload.courierName) {
      throw badRequest('COURIER_REQUIRED', 'Courier name is required to ship an order', {
        courierName: 'Required',
      });
    }

    /*
     * Resolved before the claim, so a bad source aborts without having moved the
     * order. It reads Source inside the transaction because an archive racing an
     * accept should be seen consistently with the write that follows it.
     */
    const sourceAssignments = transition.requiresSources
      ? await resolveSources(session, current, payload.sources)
      : null;

    // Claim with a status guard so two owners clicking at once cannot both win.
    const claimed = await Order.findOneAndUpdate(
      { ...scope, status: current.status },
      { $set: { status: transition.to } },
      { new: true, session }
    );
    if (!claimed) throw conflict('ALREADY_HANDLED', 'This order was just changed by someone else');

    // Pending never posted an entry and never took stock; every later status did.
    const committed = wasCommitted(current.status);

    await applyLedgerEffect(session, claimed, transition, actorUser, settings, committed);

    const restock =
      committed &&
      (transition.stock === 'restore' ||
        (transition.stock === 'restoreIfRequested' && payload.restock === true));
    if (restock) await stock.restore(session, claimed.items);
    if (action === 'return') claimed.restockedOnReturn = restock;

    /*
     * The name is copied onto the line, not just the id. From here on the order
     * renders its own history even if the source is renamed or archived, which
     * is the same promise the price snapshot already makes.
     */
    if (sourceAssignments) {
      claimed.items.forEach((item) => {
        const assigned = sourceAssignments.get(String(item._id));
        item.source = assigned._id;
        item.sourceNameBn = assigned.name;
      });
    }

    const now = new Date();
    if (transition.timestampField) claimed[transition.timestampField] = now;
    if (action === 'cancel') {
      claimed.cancelReason = payload.reason;
      claimed.cancelledBy = actorUser._id;
    }
    if (transition.requiresCourier) {
      claimed.courier = { name: payload.courierName, trackingNumber: payload.trackingNumber };
    }
    /*
     * Rendered from the same inputs the preview used and queued in this
     * transaction, so the SMS exists if and only if the status change commits.
     * The outbox sends it after commit; nothing leaves from in here.
     */
    let customerSmsQueued = false;
    if (sendCustomerSms) {
      const message = await customerSms.buildCustomerSms({
        order: claimed,
        action,
        courierName: payload.courierName,
        trackingNumber: payload.trackingNumber,
        reason: payload.reason,
        session,
      });
      await enqueueCustomerSms(
        {
          phoneE164: message.phone,
          text: message.text,
          eventType: EVENT_FOR_ACTION[action],
          orderId: claimed._id,
        },
        { session }
      );
      customerSmsQueued = true;
    }

    claimed.statusHistory.push({
      status: transition.to,
      at: now,
      by: actorUser._id,
      note: payload.reason || payload.note,
      ...(customerSmsQueued ? { customerSmsQueued: true } : {}),
    });
    await claimed.save({ session });

    return claimed;
  });

  /*
   * How the order ended, against the buyer rather than against the order. A
   * number that is delivered to nine times out of ten is a different
   * proposition from one that refuses half its parcels at the door, and on cash
   * on delivery that difference is the owner's courier bill.
   */
  await customers.recordOutcome(order);

  /*
   * Every status the owner moves an order into is news the reseller is waiting
   * for, because they are the one who told the customer it was coming. The
   * reason travels with it: on a cancellation it is the entire message.
   */
  const eventType = EVENT_FOR_ACTION[action];
  if (eventType) {
    const profile = await ResellerProfile.findById(order.reseller);
    await notifyReseller(profile, eventType, {
      data: {
        orderId: order._id,
        orderCode: order.orderCode,
        status: order.status,
        reason: payload.reason || undefined,
        courierName: payload.courierName || undefined,
      },
    });
  }

  return order;
}

/**
 * Turns the owner's chosen sources into one source document per line.
 *
 * Every line needs one. A half-assigned order is worse than an unassigned one:
 * the packing list would look complete while quietly omitting where two of the
 * crates are meant to come from, and nothing downstream would notice.
 *
 * Archived sources are refused. Archiving is how the owner retires an orchard,
 * and a retired orchard is not somewhere today's order can be collected from,
 * even though every order that already names it keeps rendering perfectly.
 */
async function resolveSources(session, order, assignments) {
  const chosen = new Map(
    (assignments || []).map((entry) => [String(entry.itemId), String(entry.sourceId)])
  );

  const missing = order.items.filter((item) => !chosen.has(String(item._id)));
  if (missing.length > 0) {
    throw badRequest('SOURCE_REQUIRED', 'Choose a source for every item before accepting', {
      sources: `Missing for ${missing.length} item(s)`,
    });
  }

  const wanted = [...new Set(chosen.values())];
  const sources = await Source.find({ _id: { $in: wanted }, isArchived: false }).session(session);
  const byId = new Map(sources.map((source) => [String(source._id), source]));

  const unknown = wanted.filter((id) => !byId.has(id));
  if (unknown.length > 0) {
    throw badRequest('SOURCE_UNKNOWN', 'One of those sources no longer exists', {
      sources: 'Unknown or archived source',
    });
  }

  return new Map(
    order.items.map((item) => [String(item._id), byId.get(chosen.get(String(item._id)))])
  );
}

/** Applies whatever the transition table says this change does to the ledger. */
async function applyLedgerEffect(session, order, transition, actorUser, settings, committed) {
  if (!transition.ledger) return;

  if (transition.ledger === 'codCollection') {
    // Prepaid orders post nothing on delivery: the reseller already has the money.
    if (order.paymentMode !== PAYMENT_MODE.COD) return;

    await ledger.postEntry(session, {
      reseller: order.reseller,
      kind: LEDGER_KIND.COD_COLLECTION_CREDIT,
      amountPoisha: order.totals.customerTotalPoisha,
      idempotencyKey: ledger.keys.codCollection(order._id),
      refType: 'order',
      refId: order._id,
      note: `Cash collected for ${order.orderCode}`,
      createdBy: actorUser._id,
    });
    return;
  }

  // An order that never reached confirmed has no entries to reverse.
  if (!committed) return;

  const open = await ledger.entriesFor('order', order._id, session);

  for (const entry of open) {
    // A returned parcel still cost a courier fee, so the delivery charge stands
    // unless the owner has chosen otherwise. The charge is the original debit
    // plus every adjustment to it, and they stand or fall together.
    const isDeliveryCharge =
      entry.kind === LEDGER_KIND.DELIVERY_DEBIT || entry.kind === LEDGER_KIND.DELIVERY_ADJUSTMENT;
    const keepDeliveryCharge =
      transition.ledger === 'reverseOnReturn' &&
      isDeliveryCharge &&
      !settings.reverseDeliveryChargeOnReturn;

    if (keepDeliveryCharge) continue;

    // eslint-disable-next-line no-await-in-loop
    await ledger.postReversal(session, entry, {
      reason: transition.to,
      note: `${order.orderCode} ${transition.to}`,
      createdBy: actorUser._id,
    });
  }
}

/* ------------------------------------------------------------- system cancels */

/**
 * Cancels every pending order of one reseller, as the system rather than as a
 * person. Used by deactivation (docs/adr/0011) and runs inside the caller's
 * transaction, so the account flip and the cancels commit or vanish together.
 *
 * Which statuses qualify comes from the transition table, and the table itself
 * refuses at load to let the system cancel anything that had committed money or
 * stock. That is why nothing here reverses an entry or restores stock: there is
 * provably nothing to reverse. A confirm racing this write conflicts with it and
 * the transaction retries, so an order is either confirmed or cancelled, never
 * confirmed and then silently cancelled.
 *
 * Customer counters and notifications are the caller's job, after commit.
 *
 * @returns {Promise<Array<{ _id: object, orderCode: string }>>} what was cancelled
 */
async function cancelPendingForReseller(
  session,
  resellerId,
  { reason = RESELLER_DEACTIVATED_REASON, now = new Date() } = {}
) {
  const transition = getTransition('cancel');

  const candidates = await Order.find(
    { reseller: resellerId, status: { $in: SYSTEM_CANCELLABLE } },
    { _id: 1, status: 1, orderCode: 1 }
  ).session(session);
  if (candidates.length === 0) return [];

  candidates.forEach((order) => assertCanTransition(order, 'cancel', SYSTEM_ACTOR));

  await Order.updateMany(
    { _id: { $in: candidates.map((o) => o._id) }, status: { $in: SYSTEM_CANCELLABLE } },
    {
      $set: {
        status: transition.to,
        [transition.timestampField]: now,
        cancelReason: reason,
        // Nobody clicked this. The owner who deactivated is in the audit log.
        cancelledBy: null,
      },
      $push: { statusHistory: { status: transition.to, at: now, note: reason } },
    },
    { session }
  );

  return candidates.map((o) => ({ _id: o._id, orderCode: o.orderCode }));
}

/* ------------------------------------------------------------- customer edit */

/** The customer fields an edit may touch. Items and quantities never. */
const CUSTOMER_EDIT_FIELDS = Object.freeze(['name', 'phoneE164', 'address', 'district']);
/** The subset the customer projection is built from; district is not in it. */
const PROJECTED_FIELDS = new Set(['name', 'phoneE164', 'address']);

/**
 * Corrects where a parcel goes and who to ring, until it has shipped.
 * PLAN-2 decision 9.
 *
 * The update is guarded on the status that was read and on the old value of
 * every changed field, so two people correcting the same order at once get a
 * clean 409 rather than one silently overwriting the other, and the `before`
 * in the audit is exactly what was replaced.
 *
 * The delivery charge is never moved here. A new district may belong to a
 * different zone, and the caller is told so; changing the charge is the owner's
 * decision through its own endpoint, which posts the ledger adjustment.
 *
 * @param {object} args
 * @param {object} args.changes any of name, phoneE164 (already normalised), address, district
 * @returns {Promise<{ order, changed: string[], before, after, deliveryZoneChanged: boolean, zone }>}
 */
async function editCustomer({ orderId, role, resellerProfile, actorUser, changes }) {
  const scope = { _id: orderId };
  if (role === ROLES.RESELLER) scope.reseller = resellerProfile._id;

  const current = await Order.findOne(scope);
  if (!current) throw notFound('Order not found');
  assertCustomerEditable(current);

  const before = {};
  const after = {};
  CUSTOMER_EDIT_FIELDS.forEach((field) => {
    if (changes[field] === undefined || changes[field] === current.customer[field]) return;
    before[field] = current.customer[field];
    after[field] = changes[field];
  });
  const changed = Object.keys(after);

  if (changed.length === 0) {
    return { order: current, changed, before, after, deliveryZoneChanged: false, zone: null };
  }

  // Refuses a district nobody delivers to, exactly as a new order would.
  let zone = null;
  let deliveryZoneChanged = false;
  if (after.district !== undefined) {
    ({ zone } = await pricing.resolveDeliveryZone(after.district));
    deliveryZoneChanged = String(zone._id) !== String(current.deliveryZone || '');
  }

  const guard = { ...scope, status: current.status };
  const $set = {};
  changed.forEach((field) => {
    guard[`customer.${field}`] = before[field];
    $set[`customer.${field}`] = after[field];
  });

  const updated = await Order.findOneAndUpdate(
    guard,
    {
      $set,
      $push: {
        statusHistory: {
          status: current.status,
          at: new Date(),
          by: actorUser._id,
          event: 'customer_edited',
          note: `Customer details changed: ${changed.join(', ')}`,
        },
      },
    },
    { new: true }
  );
  if (!updated) throw conflict('ALREADY_HANDLED', 'This order was just changed by someone else');

  // The projection is rebuilt for every number involved: a changed phone moves
  // this order from one buyer to another, and a changed name or address
  // changes the variants the buyer is recorded under.
  if (changed.some((field) => PROJECTED_FIELDS.has(field))) {
    await customers.refreshPhones([before.phoneE164, updated.customer.phoneE164]);
  }

  // The other party is told. The reseller promised the customer a delivery;
  // the owner is the one packing it. Either needs the corrected details.
  const data = {
    orderId: updated._id,
    orderCode: updated.orderCode,
    changed,
    zoneChanged: deliveryZoneChanged || undefined,
  };
  if (role === ROLES.OWNER) {
    const profile = await ResellerProfile.findById(updated.reseller);
    await notifyReseller(profile, EVENT_TYPE.ORDER_CUSTOMER_EDITED, { data });
  } else {
    await notifyOwner(EVENT_TYPE.ORDER_CUSTOMER_EDITED, {
      data: { ...data, shopName: resellerProfile?.shopName },
    });
  }

  return { order: updated, changed, before, after, deliveryZoneChanged, zone };
}

/* -------------------------------------------------------------- notifications */

async function notifyReseller(profile, eventType, message) {
  if (!profile) return;
  const user = await User.findById(profile.user);
  await notify({ user, eventType, ...message });
}

async function notifyOwner(eventType, message) {
  const owner = await User.findOne({ role: ROLES.OWNER });
  await notify({ user: owner, eventType, ...message });
}

/** Confirmed orders going stale while the fruit does not wait. */
async function agingOrders(hours) {
  const cutoff = new Date(Date.now() - hours * 60 * 60 * 1000);
  return Order.find({ status: ORDER_STATUS.CONFIRMED, confirmedAt: { $lt: cutoff } })
    .sort({ confirmedAt: 1 })
    .populate('reseller', 'shopName slug');
}

module.exports = {
  createPendingOrder,
  createManualOrder,
  confirmOrder,
  changeDeliveryCharge,
  transitionOrder,
  cancelPendingForReseller,
  editCustomer,
  agingOrders,
  postConfirmationEntries,
  LedgerEntry,
};
